### ISSUE TITLE
Set strutting to heaviest part

### ISSUE THREAD

**Issue by Jimbodiah** [Xyphos/KSP_FullAutoStrut#1]
The grandparent setting doesn't really help make the ships more stable. Could you please make a cfg file where we can select the setting we want for the strutting type?

**Comment by LouisCyfer** [comment]
also an ingame GUI or settings option will do that too! I'd really appreciate!!
suggestable options could be:

- set mod default (root part disabled, next to root, then grandparent)
- set all to root/grandparent/disabled

**Comment by Xyphos** [comment]
Grandparent creates a mesh, it should hold your vessel together just fine. if you're having stability problems, I seriously doubt it's an AutoStrut problem. Try enabling rigid attachment, but do so at your own risk.

Heaviest setting isn't supported on purpose; the mass can shift at any time, such as fuel, docking and redocking, etc. AutoStruts don't get updated when resources are used or docking so there have been problems in the past with AutoStruts on Heaviest.

There's no GUI because there's nothing to choose, it's FULLY AUTOMATIC hence the name, FullAutoStrut if you wish to add GUI code, fork and submit a pull request, but this plugin works exactly the way it's intended to.

**Comment by LouisCyfer** [comment]
orbital stations/large or heavy parted vessels with about 160 parts or similar having autostrut = root at each part avoids the Kraken more than having it to grandparent .. just saying

Ty for the reply anyways

**Comment by Jimbodiah** [comment]
I use SSTU with large launchers in RSS and setting to GrandParent does nothing for stability, rockets wobble into destruction right away. I always set to Heaviest Part and that makes it one rigid column.
